// go-htmx-vue-islands/web/islands/LikeButton.vue
<script setup lang="ts">
import { ref } from "vue";

const props = defineProps<{ postId: number; initialLikes: number }>();

const likes = ref(props.initialLikes);
const loading = ref(false);

async function like() {
  if (loading.value) return;
  loading.value = true;
  try {
    const res = await fetch(`/posts/${props.postId}/like`, { method: "POST" });
    if (!res.ok) throw new Error(`request failed: ${res.status}`);
    const data = await res.json();
    likes.value = data.likes;
  } finally {
    loading.value = false;
  }
}
</script>

<template>
  <button @click="like" :disabled="loading">♥ {{ likes }}</button>
</template>

// go-htmx-solid-islands/web/islands/LikeButton.tsx
import { createSignal } from "solid-js";

export default function LikeButton(props: {
  postId: number;
  initialLikes: number;
}) {
  const [likes, setLikes] = createSignal(props.initialLikes);
  const [loading, setLoading] = createSignal(false);

  async function like() {
    if (loading()) return;
    setLoading(true);
    try {
      const res = await fetch(`/posts/${props.postId}/like`, {
        method: "POST",
      });
      if (!res.ok) throw new Error(`request failed: ${res.status}`);
      const data = await res.json();
      setLikes(data.likes);
    } finally {
      setLoading(false);
    }
  }

  return (
    <button onClick={like} disabled={loading()}>
      ♥ {likes()}
    </button>
  );
}
